services:
  backend:
    build: ./backend
    ports:
      - "8080:8080"
    environment:
      SPRING_DATASOURCE_URL: jdbc:postgresql://db:5432/ecommForAll
      SPRING_DATASOURCE_USERNAME: postgres
      SPRING_DATASOURCE_PASSWORD: postgres
    depends_on:
    - db

  db:
    image: postgres:15
    restart: always
    environment:
      POSTGRES_DB: ecommForAll
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    ports:
      - "5432:5432"
    volumes:
      - db_data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres -d ecommForAll"]
      interval: 10s
      retries: 5
  frontend:
    build: ./frontend
    ports:
      - "3000:3000"
    # Mount the local frontend code to the container for live reloading (development only)
    volumes:
      - ./frontend:/app
      - /app/node_modules
    depends_on:
      - backend
volumes:
  db_data:
