services:
  backend:
    build: ./backend
    env_file:
      - ./backend/.env.aws
      - ./backend/.env.ai
    ports:
      - "8080:8080"
    volumes:
      - ./backend/ecommforall-ai-key.json:/app/ecommforall-ai-key.json:ro
    environment:
      SPRING_DATASOURCE_URL: jdbc:postgresql://db:5432/ecommforall
      SPRING_DATASOURCE_USERNAME: postgres
      SPRING_DATASOURCE_PASSWORD: postgres
      GOOGLE_CLOUD_PROJECT_ID: ecommforall-ai
      GOOGLE_CLOUD_LOCATION: europe-west4
      GOOGLE_APPLICATION_CREDENTIALS: /app/ecommforall-ai-key.json
    depends_on:
    - db

  db:
    image: pgvector/pgvector:pg15
    restart: always
    environment:
      POSTGRES_DB: ecommforall
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    ports:
     - "5433:5432"
    volumes:
      - db_data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres -d ecommforall"]
      interval: 10s
      retries: 5
  frontend:
    build: ./frontend
    ports:
      - "3000:3000"
    environment:
      - HOST=0.0.0.0
    # Mount the local frontend code to the container for live reloading (development only)
    volumes:
      - ./frontend:/app
      - /app/node_modules
    depends_on:
      - backend
volumes:
  db_data:
