spring:
  application:
    name: backend
  datasource:
    url: jdbc:postgresql://localhost:5432/ecommforall
    driver-class-name: org.postgresql.Driver
    username: postgres
    password: postgres
  jpa:
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
    hibernate:
      ddl-auto: update
    show-sql: true
  security:
    user:
      name: admin
      password: admin
  ai:
    vectorstore:
      pgvector:
        initialize-schema: true
        index-type: HNSW
        distance-type: COSINE_DISTANCE
        max-document-batch-size: 10000
        dimensions: 768
    vertex:
      ai:
        gemini:
          project-id: ${GCLOUD_PROJECT:ecommforall-ai}
          location: europe-west1
          chat:
            options:
              model: gemini-2.5-pro
              temperature: 0.7
        embedding:
          project-id: ${GCLOUD_PROJECT:ecommforall-ai}
          location: europe-west1
          text:
            options:
              model: text-embedding-005
    chat:
      memory:
        max-conversation-length: 10
        repository:
          jdbc:
            initialize-schema: always
            platform: postgresql
chatbot:
  max-messages: 20
  session-timeout-hours: 24
  enable-tools: true
jwt:
  secret: K6E9X7fAbC2D3eF4gH5iJ6kL7mN8oP9qR0sT1uVwXyZ1a2B3c4D5e6F7g8H9i0JkLmNoPqRsTuVwXyZ1234567890
  expiration: 86400000

springdoc:
  swagger-ui:
    path: /swagger-ui.html
  api-docs:
    path: /v3/api-docs

aws:
  s3:
    bucket: ecommforall
  region: eu-north-1

logging:
  level:
    org:
      springframework:
        ai:
          vertex: DEBUG
          chat: DEBUG
        security: DEBUG
        web:
          client: DEBUG
    com:
      ainan:
        ecommforallbackend:
          service: DEBUG
          util:
            VectorConverter: DEBUG
    root: INFO
